### ISSUE TITLE
[Feature] Activation via SideBar like Autoshutdown

### ISSUE THREAD

**Issue by OllisGit** [OllisGit/Octoprint-AutostartPrint#1]

**Comment by lloyb** [comment]
Hi Olli, Sorry I should have posted this in here, I'm new to using Github.
No rush on this, Just a time saver update really.

Thank you!

**Comment by OllisGit** [comment]
@lloyb new version 1.1.0 is out.

Please test and give me a feedback.

Thx, 
Olli

**Comment by lloyb** [comment]
Its working Great Olli, Thank you!
