### ISSUE TITLE
[Enhancement] AutoPrint when state is Operational

### ISSUE THREAD

**Issue by notms** [OllisGit/Octoprint-AutostartPrint#6]
Hello, awesome work on this plugin. Was curious to see if you could add a feature that when the State = Operational to start another print job automatically. Yes it is dangerous I am aware but you can put big letters to use at your own risk :-) I started modifying your code and removed the check for the initial connection but that sets to print as a loop. Thanks again for awesome work. I am printing face shields and this would be helpful as I have GCODE that waits for my heated bed to cool down and then I have a blade that comes to remove the print and would love to start the print automatically.

**Comment by notms** [comment]
Thank you for setting it as an enhancement, I've been playing with the code and on line102 I set:
if (Events.PRINT_DONE == event and self._settings.get_boolean([SETTINGS_KEY_ACTIVATED])): vs. looking for a connected event. My thought process was if I start the print manually it will continue to print the next one as long as the event of PRINT_Done was true, unfortunately I see the pop up on front end but no action to set the actual next print to go. If you could provide any feedback I would very much appreciate it. Thank you again

**Comment by notms** [comment]
Quick update, this was not working because there was a conflict with "After print job completes" GCODE scripts in Octoprint, I removed it and it started working as long as the print job is done. This is a hack but an real option with a checkbox would be awesome. I will incorporate my cleanup job in the file.

**Comment by OllisGit** [comment]
Hi @notms ,
the implementation is done. Here is the new option in the settings-menu:
![image](https://user-images.githubusercontent.com/24205767/80273219-a81cca00-86d0-11ea-8c0c-b8b455322afa.png)
Currently I am testing different environments, because this plugin was not tested with Phython 3 and OP1.4

**Comment by OllisGit** [comment]
New release is out!
