### ISSUE TITLE
Endless printing Not working

### ISSUE THREAD

**Issue by WilliamAr98** [OllisGit/Octoprint-AutostartPrint#7]
Hello and thanks for this plugin, its exactly what i was looking for. Now i just need it to work.

Goal:
Be able to upload multiple gcode files to octoprint, and have the printer print one, then push the part of the bed using custom gcode and then print the next file and so on.

Issue: 
Prints do not start, even if i start the first print manually it doesn't start the second file after the first one is finished. 

Note:
When i change the setting "Trigger for starting" to connected with octoprint then it starts the first file as intended. But i just can't get endless mode to start any prints for me. Also im not using folders just simply uploading a few gcode files to octoprint

Have you ran into this issue before or can this be caused by some of my other plugins i have installed? If i dont get this working i will try to code my own plugin but i would rather not have to reinvent the wheel if you know what i mean, Thanks for any help.

Picture of my settings:
![octoprintAutoPrint](https://user-images.githubusercontent.com/64912604/81193456-b36ad200-8fbb-11ea-9dfe-d05a7e0ddb63.png)

**Comment by OllisGit** [comment]
Hi @WilliamAr98 ,
I think I found the bug and fixed it.

Please test and give feedback (you can use my DryRun-Plugin for testing to not waste energy and material).

PS. sorry for the delay, but I was busy with my other new plugins : PrintJobHistory and SpoolManager.

**Comment by OllisGit** [comment]
No feedback!
