### ISSUE TITLE
print jobs not autostarting

### ISSUE THREAD

**Issue by sceptre357** [OllisGit/Octoprint-AutostartPrint#8]
Hello sir, i have several 3D printers and want to be able to upload files to watch folders and then have the printer take this newly uploaded file and immediately start printing without doing anything else. it doesnt seem to be working, when i  upload the file, while my printer is already online but nothing happens. is something wrong or is this not a feature available with your plugin?

if this isnt yet possible can you please include this feature asap? i will happily make donation..

**Comment by OllisGit** [comment]
Hi @sceptre357,

this is not the intension of the plugin. Did you read the readme on the starting page?
https://github.com/OllisGit/Octoprint-AutostartPrint
 
How do you upload the file, e.g. if you use Cura there is on option for autostart.
![image](https://user-images.githubusercontent.com/24205767/107808322-aad4d280-6d69-11eb-81e6-17d9333767c6.png)

If you upload files via drag&drop you could upload multiple files, which one should be used?
hmm...maybe an "observable autostart-folder" all files are sorted against upload timestamp and processed one after an other. What do you think?

btw,. did you saw this plugin: https://plugins.octoprint.org/plugins/continuousprint/

**Comment by dkalinai** [comment]
I think the original report is valid. I installed the plugin, uploaded a GCode file to the folder. Disconnected the printer and connected it again.

![image](https://user-images.githubusercontent.com/12793954/111534466-af2d4a80-8770-11eb-8c86-c4078766e510.png)

Saw this screen, the correct and latest .gcode file was loaded, everything looks great, printer connected etc. But after timer runs out screen disappears and nothing happens. No print is started or loaded.
